### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by Luongzz** [aiko-chan-ai/Discord-SB-Stream#3]
Làm sao để đẩy chất lượng video trên youtube thành 1080 vậy?

**Comment by aiko-chan-ai** [comment]
vấn đề là sử dụng ytdl-core chỉ hỗ trợ video 360p (nó có tiếng), từ 360p trở lên thì không nhé bạn
hoặc bạn sử dụng y2mate-api để có chất lượng video cao (có nhiều bug)

**Comment by aiko-chan-ai** [comment]
youtube-dl

**Comment by Luongzz** [comment]
![image](https://github.com/aiko-chan-ai/Discord-SB-Stream/assets/37655807/c91ee2ac-e9fc-4822-bbf5-fb4164df7f5d)
làm sao để khắc phục việc bị cắt 1 khoảng màn hình thôi nhỉ?

**Comment by Luongzz** [comment]
> vấn đề là sử dụng ytdl-core chỉ hỗ trợ video 360p (nó có tiếng), từ 360p trở lên thì không nhé bạn hoặc bạn sử dụng y2mate-api để có chất lượng video cao (có nhiều bug) 🇻🇳

sau khi hỏi gpt lòi l thì tôi có ra được file này chạy được 1080p lẫn âm thanh.

https://www.mediafire .com/file/bssyx216aqrz2q5/play.js/file

**Comment by Luongzz** [comment]
> vấn đề là sử dụng ytdl-core chỉ hỗ trợ video 360p (nó có tiếng), từ 360p trở lên thì không nhé bạn hoặc bạn sử dụng y2mate-api để có chất lượng video cao (có nhiều bug) 🇻🇳

Mặc dù không lên được 1080p nhưng tôi có thể cho nó lên 720p https://www.mediafire. com/file/bssyx216aqrz2q5/play.js/file

**Comment by aiko-chan-ai** [comment]
Bạn phải tìm hiểu thêm puppeteer

**Comment by Luongzz** [comment]
> Bạn phải tìm hiểu thêm puppeteer

Mình chuyển về null và mọi thứ ok

**Comment by SilentKiller345** [comment]
For Streaming Youtube Videos in 1080p You can use ytdl to download an audio of the video and then video with 1080p resolution which has no sound and then merge them using ffmpeg and stream it.

**Comment by aiko-chan-ai** [comment]
very slow
