### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by Luongzz** [aiko-chan-ai/Discord-SB-Stream#4]
Hiện tại play không thể đọc được đường link livestream trên youtube. Bạn có thể tham khảo qua code mình đã chỉnh sửa một chút: https://www.mediafire.com/file/426ujzu2vt6m0pv/play.js/file

**Comment by aiko-chan-ai** [comment]
Bạn có thể tạo 1 PR (Pull Request) cho tiện nhé

**Comment by aiko-chan-ai** [comment]
Ely đã thay đổi code giống như bạn rồi nên pr đó giữ lại sau nhé
