### ISSUE TITLE
[Question] Subtitles On Stream

### ISSUE THREAD

**Issue by SilentKiller345** [aiko-chan-ai/Discord-SB-Stream#5]
Is is possible to add subtitles to a live video on a vc? if yes, i need an example.

**Comment by aiko-chan-ai** [comment]
You can get ffmpeg to render the subtitles on the video output, see https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo

**Comment by SilentKiller345** [comment]
Thanks for the help!
