### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Luongzz** [aiko-chan-ai/Discord-SB-Stream#6]
![image](https://github.com/aiko-chan-ai/Discord-SB-Stream/assets/37655807/37da16ab-9b77-476c-be75-2985c38002ee)
Khi mình bắt đầu sử dụng lệnh play thì bắt đầu vấn đề này xảy ra dù trên phiên bản cũ hay mới

**Comment by aiko-chan-ai** [comment]
Ytdl issue
https://github.com/fent/node-ytdl-core/issues/1250
