### ISSUE TITLE
DiscordStreamClientError: Invalid stream (No metadata)

### ISSUE THREAD

**Issue by ichsanulaulia** [aiko-chan-ai/Discord-SB-Stream#7]
DiscordStreamClientError: Invalid stream (No metadata)
    at /home/Desktop/Discord-SB-Stream/node_modules/discord-stream-client/dist/index.js:1337:13
    at new Promise (<anonymous>)
    at Player.validateInputMetadata (/home/Desktop/Discord-SB-Stream/node_modules/discord-stream-client/dist/index.js:1322:12)
    at /home/Desktop/Discord-SB-Stream/node_modules/discord-stream-client/dist/index.js:1357:25
    at handleCallback (/home/Desktop/Discord-SB-Stream/node_modules/fluent-ffmpeg/lib/ffprobe.js:106:9)
    at handleExit (/home/Desktop/Discord-SB-Stream/node_modules/fluent-ffmpeg/lib/ffprobe.js:190:20)
    at ChildProcess.<anonymous> (/home/Desktop/Discord-SB-Stream/node_modules/fluent-ffmpeg/lib/ffprobe.js:235:11)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'STREAM_INVALID'
}

**Comment by aiko-chan-ai** [comment]
## install ffmpeg & ffprobe
https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/
https://www.golinuxcloud.com/ubuntu-install-ffprobe/
## edit code
```js
const { Client, Message } = require('discord.js-selfbot-v13');
const ytdl = require('ytdl-core');
const getYouTubeID = require('get-youtube-id');

module.exports = {
	name: 'play',
	/**
	 * @param {Client} client
	 * @param {Message} message
	 * @param {string[]} args
	 * @returns {Promise<void>}
	 */
	run: async (client, message, args) => {
		if (!client.streamClient.connection)
			return message.reply('Not connected to a voice channel');
		let url = args.join(' ');
		if (!url) return message.reply('No URL provided');
		if (client.player) client.player.stop();
		const videoId = getYouTubeID(url);
		if (videoId) {
			try {
				url = await ytdl.getInfo(videoId).then((info) => {
					const format = ytdl.chooseFormat(info.formats, {
						quality: 'highest',
						filter: 'audioandvideo',
					});
					return format.url;
				});
			} catch (e) {
				message.reply('Error getting video info');
				return console.log(e);
			}
		}
		client.player = client.streamClient.createPlayer(
			url,
			client.streamClient.connection?.streamConnection?.udp ||
				client.streamClient.connection.udp,
		);
		client.player.play({
			volume: 1,
			hwaccel: false,
			kbpsAudio: 128,
			kbpsVideo: 2500,
		});
		client.player.on('start', () => {
			message.reply('Started playing');
		});
		client.player.on('finish', () => {
			message.reply('Finished playing');
			client.player = null;
		});
	},
};
```
`Commands/play.js`

**Comment by ichsanulaulia** [comment]
actually its already fixed , im using linux then already change some codes , but thanks for answer it <3
